import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Suggestions from "@/components/Suggestions";
import { Web3Provider } from "@/contexts/Web3Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social Media DApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Web3Provider>
      <html lang="en">
        <body className={inter.className}>
          <div>
            <div className="border-b border-gray-700">
              <Navbar />
            </div>
            <div className="">
              <div className="flex justify-between max-w-6xl mx-auto">
                <div className="hidden sm:inline border-r border-gray-700 h-screen">
                  <Sidebar />
                </div>
                <div>
                  {children}
                </div>
                <div className="border-l border-gray-700 lg:flex-col p-3 h-screen hidden lg:flex w-[24rem]">
                  <div className="sticky top-0 py-2">
                    <input type="text" placeholder="Search" className="bg-gray-500 border border-gray-600 rounded-3xl text-sm w-full px-4 py-2" name="" id="" />
                  </div>
                  <Suggestions />
                </div>
              </div>
            </div>
          </div>

        </body>
      </html>
    </Web3Provider>
  );
}
